### ISSUE TITLE
Idiomatic PropTypes

### ISSUE THREAD

**Issue by craigbilner** [pinterest/react-pinterest#3]
Where PropTypes are "enums" would it be better to use:

    React.PropTypes.oneOf(['a', 'b']);

**Comment by zackargyle** [comment]
Absolutely! I've never used that one, but it sure seems like a perfect fit. I would gladly welcome a PR. :)

**Comment by craigbilner** [comment]
Perhaps we should put in some tests and linting rules first to make PRs more manageable?

**Comment by sotayamashita** [comment]
+1

**Comment by zackargyle** [comment]
Updated the PropTypes. Going to close this one and open a new one for tests/linters. That's a great idea.
