### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by jrf0110** [pinterest/react-pinterest#4]
```
sh: babel: command not found
```

If `prepublish` is being used, you can likely take out the `postinstall` directive. See https://docs.npmjs.com/misc/scripts#common-uses

If you really want to use `postinstall`, then you have to ensure that `babel` is installed on consumers' computers by specifying it as a dependency, and referencing it from react-pinterest's local `.bin`.

I think the solution here would be to just remove the `postinstall` directive since this is already taken care of in `prepublish`.

**Comment by zackargyle** [comment]
Merged a PR adding a .babelrc file and including babel-cli as a devDependency. Have not updated npm yet, but should be fixed!

**Comment by jrf0110** [comment]
Very good. This should solve the error.

However, I would recommend just using `prepublish` to build the assets; It will make installation faster and more reliable. Just my two cents, though!

Thanks for the react pinterest lib, guys! Awesome stuff :heart: :heart:
