### ISSUE TITLE
Not compatible with server side rendering

### ISSUE THREAD

**Issue by growlsworth** [pinterest/react-pinterest#6]
It currently gets hung up on this line when requiring:
https://github.com/pinterest/react-pinterest/blob/master/src/components/PinItButton.js#L148

Then when rendering it needs `window` and `location`.

**Comment by zackargyle** [comment]
Put together a PR for you, haven't had a chance to test it thoroughly, but give it a try and feel free to comment.

https://github.com/pinterest/react-pinterest/pull/9
