### ISSUE TITLE
webpack required for postinstall

### ISSUE THREAD

**Issue by growlsworth** [pinterest/react-pinterest#7]
Hey pinterest,

Thanks for this library. I wanted to request that webpack is removed from required dependencies. Because of this line: https://github.com/pinterest/react-pinterest/blob/master/package.json#L34 , webpack needs to be part of my production machines instead of part of my build process. It would be great to publish all the post compiled assets to npm and not have to have this script executed on post install. Thanks!

**Comment by zackargyle** [comment]
This should be fixed in 1.0.4 :)
